(import (chicken condition) (chicken load))
(include-relative "syntax.scm")
(define-syntax either
  (syntax-rules ()
    ((_ f ...)
     (∃ ((ω (condition-case ((λ () f ...))
              (e (exn) (left (get-condition-property e 'exn 'message))))))
       (? (left? ω) ω (right ω))))))
(define-syntax for
  (syntax-rules (← ▽ yield)
    ((_ ▽ △ (yield α) Ω ...) (△ (right α)))
    ((_ ▽ △ (← α β)  ω Ω ...) (break-left △ (>>= (λ (α) (for ▽ △ ω Ω ...)) β)))
    ((_ ▽ △ (  α β)  ω Ω ...) (>>= (λ (α) (for ▽ △ ω Ω ...)) (right β)))
    ((_ ▽ △                ω)  ω)
    ((_                α ...) (call/cc (λ (△) (for ▽ △ α ...))))))
(← (right ω) `(R . ,ω))
(← (left ω) `(L . ,ω))
(← (right? ω) (? (pair? ω) (eq? 'R (↑ ω)) #f))
(← (left? ω) (? (pair? ω) (eq? 'L (↑ ω)) #f))
(← (either? ω) (∨ (left? ω) (right? ω)))
(← (get Fω) (? (right? Fω) (↓ Fω) (error (↓ Fω))))
(← (get-or-else α Fω) (? (right? Fω) (↓ Fω) α))
(← (ensure p e ω) (? p (right ω) (left e)))
(← (⊙ f Fω) (? (∧ (either? Fω) (right? Fω)) (right (f (↓ Fω))) Fω))
(← (⊙_ f Fω) (? (∧ (either? Fω) (left? Fω)) (left (f (↓ Fω))) Fω))
(← (⊙⊙ g f Fω) (⊙_ g (⊙ f Fω)))
(← (⊥ FFω) (? (right? FFω) (↓ FFω) FFω))
(← (>>= f Fω) (⊥ (⊙ f Fω)))
(← (*> Fω Fα) (>>= (K Fα) Fω))
(← ($> Fω α) (*> Fω (right α)))
(← (● Ff Fω) (>>= (λ (ω) (⊙ (λ (f) (f ω)) Ff)) Fω))
(← (lift2 f Fα Fω) (● (⊙ (C f) Fα) Fω))
(← (break-left △ Fω) (? (left? Fω) (△ Fω) Fω))
(← (sequence Fω) (call/cc (λ (△) 
  (foldr (λ (α acc) (break-left △ (lift2 ⊂ α acc))) (right ∅) Fω))))
(← (traverse f Fω) (sequence (∀ f Fω)))

; example
;(← z 
;  (for (← x (right 1))
;       (← y (right 2))
;       (← z (right 3))
;       (yield (list x y z))))
