(import (chicken load) (chicken sort) srfi-1)
(include-relative "syntax.scm")
(include-relative "monad.scm")
(← (I ω) ω)
(← (K ω) (λ (α) ω))
(← (C f) (λ (ω) (λ (α) (f ω α))))
(← (D f . ω) (λ (α) ($ f `(,@ω ,α))))
(← (S g f) (λ (ω) (g ω (f ω))))
(← (SS g f) (λ (α ω) (g α (f ω))))
(← (J h g f) (λ (ω) (h (g ω) (f ω))))
(← (JJ h g f) (λ (α ω) (h (g α) (f ω))))
(← (O g f) (λ (α ω) (g (f α) (f ω))))
(← (&&& . fs) (λ (ω) (∀ ((C (⍨ $$)) ω) fs)))
(← (*** . fs) (λ (ωs) (∀ $$ fs ωs)))
(← & (⍨ $$))
(← (∧∧ α ω) (∧ α ω))
(← (∨∨ α ω) (∨ α ω))
(← (ι n ω) (either (list-ref ω n)))
(← (∈ k ω) (∃ ((α (assoc k ω))) (⊙ ↑↓ (ensure α (◇ "key not found: "k) α))))
(← (conj α ω) `(,@α ,ω)) (← ⊃ conj)
(← (↑n n ω) (∃ ((α (ρ ω))) (? (> n α) (take ω α) (take ω n))))
(← (↓n n ω) (∃ ((α (ρ ω))) (? (> n α) (drop ω α) (drop ω n))))
(← (⍋ f ωs) (sort ωs f))
