(import (chicken condition) (chicken format) (chicken read-syntax)
        (chicken sort) (chicken string) srfi-1)

(define-syntax λ (syntax-rules () ((_ . ω) (lambda . ω))))
(define-syntax λλ (syntax-rules () ((_ . ω) (case-lambda . ω))))
(define-syntax ? (syntax-rules () ((_ . ω) (if . ω))))
(define-syntax ← (syntax-rules () ((_ . ω) (define . ω))))
(define-syntax ∃ (syntax-rules () ((_ . ω) (let* . ω))))
(define-syntax ∃▽ (syntax-rules () ((_ . ω) (letrec . ω))))
(define-syntax ∨ (syntax-rules () ((_ . ω) (or . ω))))
(define-syntax ∧ (syntax-rules () ((_ . ω) (and . ω))))
(← ↑ car) (← ↓ cdr) (← ↑↓ cadr) (← ↑↑ caar) (← ↓↓ cddr) (← ∘ compose)
(← ≡ equal?) (← ∅ '()) (← ∅? null?) (← ρ length) (← ρs string-length) (← ◇ conc) 
(← ⊂ cons) (← ∀ map) (← $ apply) (← ⊖ reverse) (← ($$ f ω) (f ω)) 
(← ⇒ foldr) (← ⇐ foldl) (← ¬ not) (← ⍨ flip) (← ∀∀ for-each) (← ∞ +inf.0)
(← ⊆ list) (← ∀? filter)
(← (I ω) ω)
(← (K ω) (λ (α) ω))
(← (C f) (λ (ω) (λ (α) (f ω α))))
(← (D f . ω) (λ (α) ($ f `(,@ω ,α))))
(← (S g f) (λ (ω) (g ω (f ω))))
(← (SS g f) (λ (α ω) (g α (f ω))))
(← (J h g f) (λ (ω) (h (g ω) (f ω))))
(← (JJ h g f) (λ (α ω) (h (g α) (f ω))))
(← (O g f) (λ (α ω) (g (f α) (f ω))))
(← (&&& . fs) (λ (ω) (∀ ((C (⍨ $$)) ω) fs)))
(← (*** . fs) (λ (ωs) (∀ $$ fs ωs)))
(← & (⍨ $$))
(← (tap f ω) (f ω) ω)
(← (∧∧ α ω) (∧ α ω))
(← (∨∨ α ω) (∨ α ω))
(← (∈ k ω) (∃ ((α (assoc k ω))) (⊙ ↑↓ (ensure α (◇ "key not found: "k) α))))
(← (conj α ω) `(,@α ,ω)) (← ⊃ conj)
(← (↑n n ω) (∃ ((α (ρ ω))) (? (> n α) (take ω α) (take ω n))))
(← (↓n n ω) (∃ ((α (ρ ω))) (? (> n α) (drop ω α) (drop ω n))))
(← (⍋ f ωs) (sort ωs f))

(define-record-type right
  (right value)
  right?
  (value right-value))

(define-record-printer (right ω port)
  (fprintf port "#R(~S)" (right-value ω)))

(set-sharp-read-syntax! #\R (λ (port) `(right ,(↑ (read port)))))

(define-record-type left
  (left value)
  left?
  (value left-value))

(define-record-printer (left ω port)
  (fprintf port "#L(~S)" (left-value ω)))

(set-sharp-read-syntax! #\L (λ (port) `(left ,(↑ (read port)))))

(define-syntax either
  (syntax-rules ()
    ((_ f ...)
     (∃ ((ω (condition-case ((λ () f ...))
              (e (exn) (left (get-condition-property e 'exn 'message))))))
       (? (left? ω) ω (right ω))))))

(define-syntax for
  (syntax-rules (← ▽ yield)
    ((_ ▽ △ (yield α) Ω ... ) (△ (right α)))
    ((_ ▽ △ (← α β)  ω Ω ...) (△+_ △ (>>= (λ (α) (for ▽ △ ω Ω ...)) β)))
    ((_ ▽ △ (  α β)  ω Ω ...) (>>= (λ (α) (for ▽ △ ω Ω ...)) (right β)))
    ((_ ▽ △                ω)  ω)
    ((_                α ...) (call/cc (λ (△) (for ▽ △ α ...))))))

(← _+ right-value) (← +_ left-value) (← _+? right?) (← +_? left?)
(← (either? Fω) (∨ (+_? Fω) (_+? Fω)))
(← (either-guard f Fω) (? (either? Fω) (f Fω) (error "not either" Fω)))
(← (gett Fω) (? (_+? Fω) (_+ Fω) (error (+_ Fω))))
(← get (D either-guard gett))
(← (ensure p e ω) (? p (right ω) (left e)))
(← (fmapp f Fω) (? (_+? Fω) (right (f (_+ Fω))) Fω))
(← (fmap f Fω) (either-guard (D fmapp f) Fω))
(← (bindd f Fω) (? (_+? Fω) (f (_+ Fω)) Fω))
(← (bind f Fω) (either-guard (D bindd f) Fω))
(← (fjoinn FFω) (bindd I FFω)) ; lol
(← (fjoin FFω) (either-guard fjoinn FFω))
(← ⊙ fmap) (← ⊥ fjoin) (← >>= bind)
(← (thenn Fα Fω) (bindd (K Fω) Fα))
(← (then Fα Fω) (>>= (either-guard K Fω) Fα))
(← (ass Fα ω) (fmapp (K ω) Fα))
(← (as Fα ω) (⊙ (K ω) Fα))
(← *> then) (← $> as)
(← (lift22 f Fα Fω) (bindd (λ (α) (fmapp (λ (ω) (f α ω)) Fω)) Fα))
(← (lift2 f Fα Fω) (>>= (λ (α) (⊙ (λ (ω) (f α ω)) Fω)) Fα))
(← (fcomposee f) (D fmapp f))
(← (fcompose f) (D ⊙ f))
(← (kleislii f) (D bindd f))
(← (kleisli f) (D >>= f))
(← ◁ fcompose) (← ◀ kleisli)
(← (break-left △ Fω) (? (+_? Fω) (△ Fω) Fω))
(← △+_ break-left)
(← (sequencee Fωs)
  (call/cc (λ (△) (⇒ (λ (α acc) (△+_ △ (lift22 ⊂ α acc))) (right ∅) Fωs))))
(← (sequence Fωs)
  (call/cc (λ (△) (⇒ (λ (α acc) (△+_ △ (lift2 ⊂ α acc))) (right ∅) Fωs))))
(← (traversee f Fωs) (sequencee (∀ f Fωs)))
(← (traverse f Fωs) (sequence (∀ f Fωs)))
(← (lmapp f Fω) (? (+_? Fω) (left (f (+_ Fω))) Fω))
(← (lmap f Fω) (either-guard (D lmapp f) Fω))
(← ⊙_ lmap)
(← (split-choicee g f Fω) (lmapp g (fmapp f Fω)))
(← (split-choice g f Fω) (⊙_ g (⊙ f Fω)))
(← (fan-inn g f Fω) (? (+_? Fω) (g (+_ Fω)) (f (_+ Fω))))
(← (fan-in g f Fω) (either-guard (D fan-inn g f) Fω))
(← +++ split-choice) (← /// fan-in)
(← (alternative . Fω) (call/cc (λ (△) (⇐ (λ (_ α) (? (_+? α) (△ α) α)) ∅ Fω))))
(← </> alternative)
(← (ι n ω) (either (list-ref ω n)))
