(import (chicken load) srfi-1)
(include-relative "syntax.scm")
(include-relative "monad.scm")
(← (I ω) ω)
(← (K ω) (λ (α) ω))
(← (C f) (λ (ω) (λ (α) (f ω α))))
(← (S g f) (λ (ω) (g ω (f ω))))
(← (J h g f) (λ (ω) (h (g ω) (f ω))))
(← (ι n ω) (either (list-ref ω n)))
(← (∈ k ω) (∃ ((α (assoc k ω))) (⊙ ↓ (ensure α (◇ "key not found: "k) α))))
(← (⊃ α ω) `(,@α ,ω)) 
(← (↑n n ω) (∃ ((α (ρ ω))) (? (> n α) (take ω α) (take ω n))))
(← (↓n n ω) (∃ ((α (ρ ω))) (? (> n α) (drop ω α) (drop ω n))))
(← (∧∧ α ω) (∧ α ω))
(← (∨∨ α ω) (∨ α ω))
