(import (chicken string))
(define-syntax λ (syntax-rules () ((_ . ω) (lambda . ω))))
(define-syntax ? (syntax-rules () ((_ . ω) (if . ω))))
(define-syntax ← (syntax-rules () ((_ . ω) (define . ω))))
(define-syntax ∃ (syntax-rules () ((_ . ω) (let* . ω))))
(define-syntax ∨ (syntax-rules () ((_ . ω) (or . ω))))
(define-syntax ∧ (syntax-rules () ((_ . ω) (and . ω))))
(← ↑ car) (← ↓ cdr) (← ↑↓ cadr) (← ↓↓ cddr) (← ∘ compose) (← ≡ equal?) (← ∅ '()) 
(← ∅? null?) (← ρ length) (← ◇ conc) (← ⊂ cons) (← ∀ map) (← $ apply)
(← ($$ f ω) (f ω)) 
(← (I ω) ω)
(← (K ω) (λ (α) ω))
(← (C f) (λ (ω) (λ (α) (f ω α))))
(← (S g f) (λ (ω) (g ω (f ω))))
(← (J h g f) (λ (ω) (h (g ω) (f ω))))
