(import (chicken string))
(define-syntax λ (syntax-rules () ((_ . ω) (lambda . ω))))
(define-syntax λλ (syntax-rules () ((_ . ω) (case-lambda . ω))))
(define-syntax ? (syntax-rules () ((_ . ω) (if . ω))))
(define-syntax ← (syntax-rules () ((_ . ω) (define . ω))))
(define-syntax ∃ (syntax-rules () ((_ . ω) (let* . ω))))
(define-syntax ∨ (syntax-rules () ((_ . ω) (or . ω))))
(define-syntax ∧ (syntax-rules () ((_ . ω) (and . ω))))
(← ↑ car) (← ↓ cdr) (← ↑↓ cadr) (← ↑↑ caar) (← ↓↓ cddr) (← ∘ compose)
(← ≡ equal?) (← ∅ '()) (← ∅? null?) (← ρ length) (← ρs string-length) (← ◇ conc) 
(← ⊂ cons) (← ∀ map) (← $ apply) (← ⊖ reverse) (← ($$ f ω) (f ω)) 
(← ⇒ foldr) (← ⇐ foldl) (← ¬ not) (← ⍨ flip)
