(import (chicken load) srfi-1)
(include-relative "../helpers/monad.scm")
(include-relative "../helpers/prelude.scm")
(include-relative "../helpers/syntax.scm")
(include-relative "../helpers/transducers.scm")
(include-relative "../transformers/common.scm")

(← (row⊥country-artist-plays row)
 (for (← rank (∈ 'artist-rank-plays row))
      (← name (∈ 'artist-name-plays row))
      (← plays (∈ 'artist-plays row))
      (yield `(,(n⊥s rank) ,name ,(n⊥s plays)))))

(← (rows⊥country-plays rows)
  (for (← row (either (↑ rows)))
       (← rank (∈ 'country-rank-plays row))
       (← id (∈ 'country-id-plays row))
       (← name (∈ 'country-name-plays row))
       (← plays (∈ 'country-plays row))
       (← artists (traverse row⊥country-artist-plays rows))
       (yield `(plays
                ((rank ,rank)
                 (id ,id)
                 (name ,name)
                 (plays ,(n⊥s plays))
                 (artists ,artists))))))

(← (row⊥country-artist-hours row)
 (for (← rank (∈ 'artist-rank-seconds row))
      (← name (∈ 'artist-name-seconds row))
      (← seconds (∈ 'artist-seconds row))
      (hours (seconds⊥hours seconds))
      (yield `(,(n⊥s rank) ,name ,hours))))

(← (rows⊥country-hours rows)
  (for (← row (either (↑ rows)))
       (← rank (∈ 'country-rank-seconds row))
       (← id (∈ 'country-id-seconds row))
       (← name (∈ 'country-name-seconds row))
       (← seconds (∈ 'country-seconds row))
       (hours (seconds⊥hours seconds))
       (← artists (traverse row⊥country-artist-hours rows))
       (yield `(hours
                ((rank ,rank)
                 (id ,id)
                 (name ,name)
                 (hours ,hours)
                 (artists ,artists))))))

; need to structure plays/hours subfields in a way that makes them easy to
; join after each pipeline runs. This is not quite there—nested list bullshit
(← country-plays-key (∘ (◀ (∈t 'id)) (◀ (∈t 'plays))))
(← country-hours-key (∘ (◀ (∈t 'id)) (◀ (∈t 'hours))))
(← (country-key ω)
  (get-or-else #f (</> (country-plays-key ω) (country-hours-key ω))))

(← pipeline
  (∘
    (mux 
      (∘ (chunk-on (◀ (∈t 'country-id-plays)))
         (⊙t sequence)
         (⊙t (◀ rows⊥country-plays)))
      (∘ (chunk-on (◀ (∈t 'country-id-seconds)))
         (⊙t sequence)
         (⊙t (◀ rows⊥country-hours))))
    ))
    ;(join-on 2 (◀ (∈t 'id)))
    ;(⊙t sequence)
    ; individual country page writes happen here
    ; top country rankings next
    ;(⊙t (◁ (∘ (λ (ω) (∀ (λ (α) (alist-delete 'artists α)) ω)))))
;    ))
    

(← EXAMPLE
   '(((country-rank-plays 1)
     (country-id-plays 236)
     (country-plays 30578)
     (country-name-plays "United States")
     (artist-rank-plays 1)
     (artist-name-plays "Tuxedomoon")
     (artist-plays 1344)
     (country-rank-seconds 1)
     (country-id-seconds 234)
     (country-seconds 8171879)
     (country-name-seconds "United Kingdom")
     (artist-rank-seconds 1)
     (artist-name-seconds "Coil")
     (artist-seconds 384004))
  ((country-rank-plays 1)
     (country-id-plays 236)
     (country-plays 30578)
     (country-name-plays "United States")
     (artist-rank-plays 2)
     (artist-name-plays "Moss Icon")
     (artist-plays 695)
     (country-rank-seconds 1)
     (country-id-seconds 234)
     (country-seconds 8171879)
     (country-name-seconds "United Kingdom")
     (artist-rank-seconds 2)
     (artist-name-seconds "Henry Cow")
     (artist-seconds 357138))
  ((country-rank-plays 1)
     (country-id-plays 236)
     (country-plays 30578)
     (country-name-plays "United States")
     (artist-rank-plays 3)
     (artist-name-plays "Arthur Russell")
     (artist-plays 613)
     (country-rank-seconds 1)
     (country-id-seconds 234)
     (country-seconds 8171879)
     (country-name-seconds "United Kingdom")
     (artist-rank-seconds 3)
     (artist-name-seconds "Talk Talk")
     (artist-seconds 340857))))
