(import (chicken load) srfi-1)
(include-relative "../helpers/monad.scm")
(include-relative "../helpers/prelude.scm")
(include-relative "../helpers/syntax.scm")
(include-relative "../helpers/transducers.scm")
(include-relative "../transformers/common.scm")

(← (row⊥country-artist-plays row)
 (for (← rank (∈ 'artist-rank-plays row))
      (← name (∈ 'artist-name-plays row))
      (← plays (∈ 'artist-plays row))
      (yield `(,(n⊥s rank) ,name ,(n⊥s plays)))))

(← (rows⊥country-plays rows)
  (for (← row (either (↑ rows)))
       (← rank (∈ 'country-rank-plays row))
       (← id (∈ 'country-id-plays row))
       (← name (∈ 'country-name-plays row))
       (← plays (∈ 'country-plays row))
       (← artists (traverse row⊥country-artist-plays rows))
       (yield `(plays
                ((rank ,rank)
                 (id ,id)
                 (name ,name)
                 (plays ,(n⊥s plays))
                 (artists ,artists))))))

(← (row⊥country-artist-hours row)
 (for (← rank (∈ 'artist-rank-seconds row))
      (← name (∈ 'artist-name-seconds row))
      (← seconds (∈ 'artist-seconds row))
      (hours (seconds⊥hours seconds))
      (yield `(,(n⊥s rank) ,name ,hours))))

(← (rows⊥country-hours rows)
  (for (← row (either (↑ rows)))
       (← rank (∈ 'country-rank-seconds row))
       (← id (∈ 'country-id-seconds row))
       (← name (∈ 'country-name-seconds row))
       (← seconds (∈ 'country-seconds row))
       (hours (seconds⊥hours seconds))
       (← artists (traverse row⊥country-artist-hours rows))
       (yield `(hours
                ((rank ,rank)
                 (id ,id)
                 (name ,name)
                 (hours ,hours)
                 (artists ,artists))))))

(← country-key (◀ (∘ (D ∈ 'id) ↑↓)))

(← (country-order α ω)
  (get-or-else #f (for (← αid (∈ 'rank α))
                       (← ωid (∈ 'rank ω))
                       (yield (< αid ωid)))))

(← (country-artists-pipeline ω f)
  (∘ (chunk-on (◀ (D ∈ ω)))
     (⊙t sequence)
     (⊙t (◀ f))))

(← (top-countries-pipeline ω n)
   (∘ (⊙t (◀ (D ∈ ω)))
      (⊙t (◁ (D alist-delete 'artists)))
      (chunk +inf.0)
      (⊙t sequence)
      (⊙t (◁ (D ⍋ country-order)))
      (⊙t (◁ (D ↑n n)))
      (⊙t (◁ (D ⊂ ω)))))

(← (transform-countries
       #!optional (country-page-html (⊙t (λ (ω) (right (print 'html))))))
  (∘ (mux (country-artists-pipeline 'country-id-plays rows⊥country-plays)
          (country-artists-pipeline 'country-id-seconds rows⊥country-hours))
     (join-on 2 country-key)
     (⊙t sequence)
     (tap-m *> country-page-html)
     ; top country rankings next
     (mux (top-countries-pipeline 'hours 15)
          (top-countries-pipeline 'plays 15))
     (chunk 2)
     (⊙t sequence)))
