#!/usr/local/bin/csi -s
(import (chicken io) (chicken load) (chicken process-context))
(load-relative "../src/helpers.scm")
(← FIELDS '(duration title album artist albumartist genre date))
(← NUMERICAL '(duration date))
(← drop-tag (? (∘ (⊥ string=? "tag") ↑) ↓ I))
(← key (∘ flatten (&&& (∘ s→x ↑) ↓)))
(← check-key (? (∘ (⊥ ∈ FIELDS) ↑) I (K #f)))
(← value (? (∘ (⊥ ∈ NUMERICAL) ↑) (&&& ↑ (∘ (⊥ $ s→n) ↓)) (&&& ↑ (∘ xs→s ↓))))
(← make-field (◀ value check-key key drop-tag s→xs))
(← (parse f) (⊥ foldr (λ (α ω) ((?? f (⊥ (⊖ ⊣) ω) (K ω)) α)) ∅))
(← make-fields (parse make-field))
(← parse-tracks (∘ (⊥ ∀ make-fields) (split-list (⊥ string=? "+===+"))))
(← open (Λ with-input-from-file % read-lines))
(← (lookup v k) ((?? (Λ assoc k %) (∘ ↑ ↓) (K "")) v))
(← csv-line (∘ (Λ xs→s % (◇ #\tab)) (λ (α) (∀ (∘ ◇ (⊥ lookup α)) FIELDS))))
(← csv (∘ (⊥ ∀ csv-line) parse-tracks open))
(← main (∘ (⊥ for-each write-line) csv ↑))
(main (command-line-arguments))
