#!/bin/sh
id="$(echo "$1" | cut -d "/" -f 5 | cut -d "-" -f 1)"
curl https://api.discogs.com/releases/$id --user-agent "jq test" | jq -r '.tracklist[] | select(.type_ == "track") | "\(.title)\t\((.duration | split(":") | .[0] | tonumber) * 60 + (.duration | split(":") | .[1] | tonumber))"'
