(import (chicken load) (chicken pretty-print))
(include-relative "./helpers/monad.scm")
(include-relative "./helpers/syntax.scm")
(include-relative "./html/main.scm")
(include-relative "./repos/artist-pages.scm")
(include-relative "./repos/artists.scm")
(include-relative "./repos/countries.scm")
(include-relative "./transformers/artist-pages.scm")
(include-relative "./transformers/artists.scm")
(include-relative "./transformers/countries.scm")

(← DB "~/.config/cmus/lolfm.db")

(pp
  (for (← _ (write-css "/tmp/lolfm" "style.css" css))
       (← artist-pages ((get-artist-pages DB) transform-artist-pages))
       (← all-countries ((get-countries DB) transform-individual-countries))
       (top-countries (sort-top-countries all-countries))
       (← _ (render-top-countries top-countries))
       (← top-artists ((get-artists DB) transform-top-artists))
       (← ok? (render-main top-artists all-countries))
       (yield all-countries))
)
