(import (chicken load) (chicken pretty-print))
(include-relative "./helpers/monad.scm")
(include-relative "./helpers/syntax.scm")
(include-relative "./html/main.scm")
(include-relative "./repos/albums.scm")
(include-relative "./repos/artist-pages.scm")
(include-relative "./repos/artists.scm")
(include-relative "./repos/countries.scm")
(include-relative "./repos/genres.scm")
(include-relative "./repos/plays.scm")
(include-relative "./repos/songs.scm")
(include-relative "./repos/years.scm")
(include-relative "./transformers/albums.scm")
(include-relative "./transformers/artist-pages.scm")
(include-relative "./transformers/artists.scm")
(include-relative "./transformers/countries.scm")
(include-relative "./transformers/genres.scm")
(include-relative "./transformers/plays.scm")
(include-relative "./transformers/songs.scm")
(include-relative "./transformers/years.scm")

(← DB "~/.config/cmus/lolfm.db")

(pp
  (for (← _ (write-css "/tmp/lolfm" "style.css" css))
       (← artist-pages ((get-artist-pages DB) transform-artist-pages))
       (← all-countries ((get-countries DB) transform-individual-countries))
       (top-countries (sort-top-countries all-countries))
       (← _ (render-top-countries top-countries))
       (← top-artists ((get-artists DB) transform-top-artists))
       (← top-albums ((get-albums DB) transform-albums))
       (← top-songs ((get-songs DB) transform-songs))
       (← top-genres ((get-genres DB) transform-genres))
       (← top-years ((get-years DB) transform-years))
       (← recent-plays ((get-plays DB) transform-plays))
       (← ok? (render-main top-artists top-albums top-songs top-genres
                           all-countries top-years))
       (yield all-countries))
)
