(← DB "~/.config/cmus/lolfm.db")

(for (← _ (write-css "/tmp/lolfm" "style.css" css))
     (← discoveries ((get-discoveries DB) (†⊙ (†↑n 15))))
     (← loved ((get-loved DB) (†⊙ (†↑n 15))))
     (← artist-pages ((get-artist-pages DB) transform-artist-pages))
     (← all-countries ((get-countries DB) transform-individual-countries))
     (top-countries (sort-top-countries all-countries))
     (← _ (render-top-countries top-countries))
     (← top-artists ((get-artists DB) transform-top-artists))
     (← top-albums ((get-albums DB) transform-albums))
     (← top-songs ((get-songs DB) transform-songs))
     (← genre-pages ((get-genre-pages DB) transform-genre-pages))
     (← top-genres ((get-genres DB) transform-genres))
     (← top-years ((get-years DB) transform-years))
     (← recent-plays ((get-plays DB) transform-plays))
     (← ok? (render-main recent-plays discoveries loved top-artists top-albums 
                         top-songs top-genres all-countries top-years))
     (yield (exit 0)))
