use sqlite::Connection;

use crate::models::er::Er;

pub fn run(db: &Connection) -> Result<(), Er> {
  let query = "
    PRAGMA foreign_keys = ON;

    CREATE TABLE IF NOT EXISTS raw_cmus_events(
      time_milliseconds BIGINT NOT NULL,
      status            INTEGER NOT NULL,
      artist            TEXT,
      title             TEXT,
      album             TEXT,
      album_artist      TEXT,
      genre             TEXT,
      disc_number       TEXT,
      track_number      TEXT,
      duration          INTEGER,
      date              TEXT
    );
    
    CREATE TABLE IF NOT EXISTS artists(
      id    INTEGER PRIMARY KEY NOT NULL,
      name  TEXT NOT NULL COLLATE NOCASE,
      UNIQUE(name COLLATE NOCASE)
    );
    
    CREATE TABLE IF NOT EXISTS albums(
      id            INTEGER PRIMARY KEY NOT NULL,
      title         TEXT NOT NULL COLLATE NOCASE,
      artist        INTEGER NOT NULL,
      year          INTEGER DEFAULT 0 NOT NULL,
      FOREIGN KEY(artist) REFERENCES artists(id),
      UNIQUE(title COLLATE NOCASE,artist)
    );
    
    CREATE TABLE IF NOT EXISTS genres(
      id    INTEGER PRIMARY KEY NOT NULL,
      name  TEXT NOT NULL COLLATE NOCASE,
      UNIQUE(name COLLATE NOCASE)
    );
    
    CREATE TABLE IF NOT EXISTS songs(
      id            INTEGER PRIMARY KEY NOT NULL,
      title         TEXT NOT NULL COLLATE NOCASE,
      artist        INTEGER NOT NULL,
      genre         INTEGER NOT NULL,
      FOREIGN KEY(artist) REFERENCES artists(id),
      FOREIGN KEY(genre) REFERENCES genres(id),
      UNIQUE(title COLLATE NOCASE,artist)
    );
    
    CREATE TABLE IF NOT EXISTS plays(
      date          INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
      song          INTEGER NOT NULL,
      album         INTEGER NOT NULL,
      duration      INTEGER DEFAULT 0 NOT NULL,
      FOREIGN KEY (song) REFERENCES songs(id),
      FOREIGN KEY (album) REFERENCES albums(id),
      UNIQUE(date)
    );
    
    CREATE TABLE IF NOT EXISTS loved(
      date          INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
      song          INTEGER NOT NULL,
      FOREIGN KEY(song) REFERENCES songs(id)
      UNIQUE(song)
    );
    
    CREATE TABLE IF NOT EXISTS suppressed(
      date          INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
      artist        INTEGER NOT NULL,
      FOREIGN KEY(artist) REFERENCES artists(id)
    );
    
    -- Migration 01. Adding countries
    CREATE TABLE IF NOT EXISTS countries(
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      abbreviation    TEXT NOT NULL DEFAULT 'XX',
      name            TEXT NOT NULL DEFAULT 'Unknown Country',
      UNIQUE(abbreviation),
      CHECK (LENGTH(abbreviation) = 2)
    );
    
    INSERT OR IGNORE INTO countries (id, abbreviation, name) 
    VALUES (0, 'XX', 'Unknown Country');

    INSERT OR IGNORE INTO countries (name, abbreviation)
    VALUES
       ('Afghanistan','AF'),
       ('Albania','AL'),
       ('Algeria','DZ'),
       ('American Samoa','AS'),
       ('Andorra','AD'),
       ('Angola','AO'),
       ('Anguilla','AI'),
       ('Antarctica','AQ'),
       ('Antigua and Barbuda','AG'),
       ('Argentina','AR'),
       ('Armenia','AM'),
       ('Aruba','AW'),
       ('Australia','AU'),
       ('Austria','AT'),
       ('Azerbaijan','AZ'),
       ('Bahamas','BS'),
       ('Bahrain','BH'),
       ('Bangladesh','BD'),
       ('Barbados','BB'),
       ('Belarus','BY'),
       ('Belgium','BE'),
       ('Belize','BZ'),
       ('Benin','BJ'),
       ('Bermuda','BM'),
       ('Bhutan','BT'),
       ('Bolivia','BO'),
       ('Bonaire, Sint Eustatius and Saba','BQ'),
       ('Bosnia and Herzegovina','BA'),
       ('Botswana','BW'),
       ('Bouvet Island','BV'),
       ('Brazil','BR'),
       ('British Indian Ocean Territory','IO'),
       ('Brunei','BN'),
       ('Bulgaria','BG'),
       ('Burkina Faso','BF'),
       ('Burundi','BI'),
       ('Cabo Verde','CV'),
       ('Cambodia','KH'),
       ('Cameroon','CM'),
       ('Canada','CA'),
       ('Cayman Islands','KY'),
       ('Central African Republic','CF'),
       ('Chad','TD'),
       ('Chile','CL'),
       ('China','CN'),
       ('Christmas Island','CX'),
       ('Cocos (Keeling) Islands','CC'),
       ('Colombia','CO'),
       ('Comoros','KM'),
       ('Democratic Republic of the Congo','CD'),
       ('Congo','CG'),
       ('Cook Islands','CK'),
       ('Costa Rica','CR'),
       ('Croatia','HR'),
       ('Cuba','CU'),
       ('Curaçao','CW'),
       ('Cyprus','CY'),
       ('Czechia','CZ'),
       ('Côte d''Ivoire','CI'),
       ('Denmark','DK'),
       ('Djibouti','DJ'),
       ('Dominica','DM'),
       ('Dominican Republic','DO'),
       ('Ecuador','EC'),
       ('Egypt','EG'),
       ('El Salvador','SV'),
       ('Equatorial Guinea','GQ'),
       ('Eritrea','ER'),
       ('Estonia','EE'),
       ('Eswatini','SZ'),
       ('Ethiopia','ET'),
       ('Falkland Islands','FK'),
       ('Faroe Islands','FO'),
       ('Fiji','FJ'),
       ('Finland','FI'),
       ('France','FR'),
       ('French Guiana','GF'),
       ('French Polynesia','PF'),
       ('French Southern Territories','TF'),
       ('Gabon','GA'),
       ('Gambia','GM'),
       ('Georgia','GE'),
       ('Germany','DE'),
       ('Ghana','GH'),
       ('Gibraltar','GI'),
       ('Greece','GR'),
       ('Greenland','GL'),
       ('Grenada','GD'),
       ('Guadeloupe','GP'),
       ('Guam','GU'),
       ('Guatemala','GT'),
       ('Guernsey','GG'),
       ('Guinea','GN'),
       ('Guinea-Bissau','GW'),
       ('Guyana','GY'),
       ('Haiti','HT'),
       ('Heard Island and McDonald Islands','HM'),
       ('Holy See','VA'),
       ('Honduras','HN'),
       ('Hong Kong','HK'),
       ('Hungary','HU'),
       ('Iceland','IS'),
       ('India','IN'),
       ('Indonesia','ID'),
       ('Iran','IR'),
       ('Iraq','IQ'),
       ('Ireland','IE'),
       ('Isle of Man','IM'),
       ('Israel','IL'),
       ('Italy','IT'),
       ('Jamaica','JM'),
       ('Japan','JP'),
       ('Jersey','JE'),
       ('Jordan','JO'),
       ('Kazakhstan','KZ'),
       ('Kenya','KE'),
       ('Kiribati','KI'),
       ('North Korea','KP'),
       ('South Korea','KR'),
       ('Kuwait','KW'),
       ('Kyrgyzstan','KG'),
       ('Laos','LA'),
       ('Latvia','LV'),
       ('Lebanon','LB'),
       ('Lesotho','LS'),
       ('Liberia','LR'),
       ('Libya','LY'),
       ('Liechtenstein','LI'),
       ('Lithuania','LT'),
       ('Luxembourg','LU'),
       ('Macao','MO'),
       ('Madagascar','MG'),
       ('Malawi','MW'),
       ('Malaysia','MY'),
       ('Maldives','MV'),
       ('Mali','ML'),
       ('Malta','MT'),
       ('Marshall Islands','MH'),
       ('Martinique','MQ'),
       ('Mauritania','MR'),
       ('Mauritius','MU'),
       ('Mayotte','YT'),
       ('Mexico','MX'),
       ('Micronesia','FM'),
       ('Moldova','MD'),
       ('Monaco','MC'),
       ('Mongolia','MN'),
       ('Montenegro','ME'),
       ('Montserrat','MS'),
       ('Morocco','MA'),
       ('Mozambique','MZ'),
       ('Myanmar','MM'),
       ('Namibia','NA'),
       ('Nauru','NR'),
       ('Nepal','NP'),
       ('Netherlands','NL'),
       ('New Caledonia','NC'),
       ('New Zealand','NZ'),
       ('Nicaragua','NI'),
       ('Niger','NE'),
       ('Nigeria','NG'),
       ('Niue','NU'),
       ('Norfolk Island','NF'),
       ('Macedonia','MK'),
       ('Northern Mariana Islands','MP'),
       ('Norway','NO'),
       ('Oman','OM'),
       ('Pakistan','PK'),
       ('Palau','PW'),
       ('Palestine','PS'),
       ('Panama','PA'),
       ('Papua New Guinea','PG'),
       ('Paraguay','PY'),
       ('Peru','PE'),
       ('Philippines','PH'),
       ('Pitcairn','PN'),
       ('Poland','PL'),
       ('Portugal','PT'),
       ('Puerto Rico','PR'),
       ('Qatar','QA'),
       ('Romania','RO'),
       ('Russia','RU'),
       ('Rwanda','RW'),
       ('Réunion','RE'),
       ('Saint Barthélemy','BL'),
       ('Saint Helena, Ascension and Tristan da Cunha','SH'),
       ('Saint Kitts and Nevis','KN'),
       ('Saint Lucia','LC'),
       ('Saint Martin','MF'),
       ('Saint Pierre and Miquelon','PM'),
       ('Saint Vincent and the Grenadines','VC'),
       ('Samoa','WS'),
       ('San Marino','SM'),
       ('Sao Tome and Principe','ST'),
       ('Saudi Arabia','SA'),
       ('Senegal','SN'),
       ('Serbia','RS'),
       ('Seychelles','SC'),
       ('Sierra Leone','SL'),
       ('Singapore','SG'),
       ('Sint Maarten','SX'),
       ('Slovakia','SK'),
       ('Slovenia','SI'),
       ('Solomon Islands','SB'),
       ('Somalia','SO'),
       ('South Africa','ZA'),
       ('South Georgia and the South Sandwich Islands','GS'),
       ('South Sudan','SS'),
       ('Spain','ES'),
       ('Sri Lanka','LK'),
       ('Sudan','SD'),
       ('Suriname','SR'),
       ('Svalbard and Jan Mayen','SJ'),
       ('Sweden','SE'),
       ('Switzerland','CH'),
       ('Syria','SY'),
       ('Taiwan','TW'),
       ('Tajikistan','TJ'),
       ('Tanzania','TZ'),
       ('Thailand','TH'),
       ('Timor-Leste','TL'),
       ('Togo','TG'),
       ('Tokelau','TK'),
       ('Tonga','TO'),
       ('Trinidad and Tobago','TT'),
       ('Tunisia','TN'),
       ('Turkmenistan','TM'),
       ('Turks and Caicos Islands','TC'),
       ('Tuvalu','TV'),
       ('Türkiye','TR'),
       ('Uganda','UG'),
       ('Ukraine','UA'),
       ('United Arab Emirates','AE'),
       ('United Kingdom','GB'),
       ('United States Minor Outlying Islands','UM'),
       ('United States','US'),
       ('Uruguay','UY'),
       ('Uzbekistan','UZ'),
       ('Vanuatu','VU'),
       ('Venezuela','VE'),
       ('Vietnam','VN'),
       ('British Virgin Islands','VG'),
       ('US Virgin Islands','VI'),
       ('Wallis and Futuna','WF'),
       ('Western Sahara','EH'),
       ('Yemen','YE'),
       ('Zambia','ZM'),
       ('Zimbabwe','ZW'),
       ('Åland Islands','AX');
    
    ALTER TABLE artists RENAME TO artists_old;
    
    CREATE TABLE IF NOT EXISTS artists(
      id        INTEGER PRIMARY KEY NOT NULL,
      name      TEXT NOT NULL COLLATE NOCASE,
      country   INTEGER NOT NULL DEFAULT 0,
      UNIQUE(name COLLATE NOCASE),
      FOREIGN KEY (country) REFERENCES countries(id)
    );
    
    INSERT INTO artists (id, name, country)
    SELECT id, name, 0 FROM artists_old;
    
    DROP TABLE artists_old;
    ";
    Ok(db.execute(query)?)
}
